Document Terraform examples
databricks/terraform-databricks-examples pull request #167
Opened 2024-12-10 16:05 UTC by micheledaddetta-databricks

Most of README files were already defined. TFDocs updated in each of them

2025-01-02 17:27 UTC, alexott requested changes
It would be nice to clarify some instructions

2025-01-02 17:27 UTC, alexott commented on examples/aws-workspace-uc-simple/README.md
> +| <a name="module_unity_catalog"></a> [unity\_catalog](#module\_unity\_catalog)                      | ../../modules/aws-databricks-unity-catalog | n/a     |
Let file a separate issue to unify source specification - in this example we use relative paths, while in other examples we're using GitHub URLs

2025-01-02 17:27 UTC, alexott commented on modules/adb-lakehouse-uc/account-principals/README.md
> +7. Run `terraform apply` to create the resources.
Hmmm. I do not exactly understand what should be done here. We need just to say:

> add `terraform.tfvars` with the information about service principals to be provisioned to account level. 

And describe how information should look like

2025-01-02 17:27 UTC, alexott commented on modules/adb-lakehouse-uc/uc-data-assets/README.md
> +7. Run `terraform apply` to create the resources.
Same here

2025-01-02 17:27 UTC, alexott commented on modules/adb-lakehouse-uc/account-principals/README.md
> +7. Run `terraform apply` to create the resources.
Users may use just locals instead of variables.

2025-01-02 17:27 UTC, alexott commented on modules/adb-lakehouse-uc/account-principals/README.md
> +7. Run `terraform apply` to create the resources.
This is not strictly required - it's just best practice, but not related to databricks

2025-01-02 17:27 UTC, alexott commented on modules/aws-databricks-base-infra/README.md
> +7. Run `terraform apply` to create the resources.
The same

2025-01-23 14:55 UTC, micheledaddetta-databricks commented on examples/aws-workspace-uc-simple/README.md
> +| <a name="module_unity_catalog"></a> [unity\_catalog](#module\_unity\_catalog)                      | ../../modules/aws-databricks-unity-catalog | n/a     |
I removed this section when using relative paths

2025-01-23 15:19 UTC, alexott approved these changes

2025-01-23 15:19 UTC, alexott commented
Thank you!

2025-01-23 15:19 UTC, merged