Adding one apply UC and workspace example
databricks/terraform-databricks-examples pull request #58
Opened 2023-04-20 00:47 UTC by flaviomalavazi

Changes:
- Creating AWS and Databricks resources to build a simple workspace with UC enabled
- Creating Databricks account level groups, promoting them to UC Metastore owners and adding permissions

2023-04-20 11:44 UTC, RodrigoLima82 approved these changes

2023-05-25 12:40 UTC, alexott requested changes
put modules into the top-level `modules` folder, so they could be visible in the Terraform registry UI.

2023-06-01 11:40 UTC, flaviomalavazi commented
> put modules into the top-level `modules` folder, so they could be visible in the Terraform registry UI.

Hey, @alexott, I've moved the modules to the top level folder, as well as updated the top level readme documentation and bumped provider versions

2023-06-01 11:56 UTC, nfx approved these changes

2023-06-05 13:38 UTC, flaviomalavazi commented on modules/aws-databricks-unity-catalog/versions.tf
> +      version = "=4.57.0"
Adjusted provider version to >=4.57

2023-06-05 13:44 UTC, flaviomalavazi commented on modules/aws-databricks-base-infra/versions.tf
> +      version = "=4.57.0"
Adjusted provider version to >=4.57

2023-06-05 13:44 UTC, flaviomalavazi commented on examples/aws-workspace-uc-simple/databricks_unity_catalog.tf
> +    principal  = local.unity_admin_group
Done!

2023-06-05 13:44 UTC, flaviomalavazi commented on examples/aws-workspace-uc-simple/databricks_clusters.tf
> +  }
Removed

2023-06-22 18:21 UTC, flaviomalavazi commented
Hey, @alexott, all good here?

2023-06-26 14:19 UTC, merged